apiVersion: v2
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.3.5
deprecated: false
description: InfluxDB v2 open source time series database for TrueNAS SCALE
home: https://truecharts.org/charts/stable/influxdb2
icon: https://avatars0.githubusercontent.com/u/5713248?s=200&v=4
keywords:
  - influxdb2
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: influxdb2
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/influxdb2
  - https://github.com/influxdata/helm-charts/tree/master/charts/influxdb2
  - https://github.com/cdr/code-server
type: application
version: 2.7.3
annotations:
  truecharts.org/category: database
  truecharts.org/SCALE-support: "true"
